######################
#       Helena       #
######################
# Data
mysql_data_helena:
  image: ubuntu
  volumes:
  - ./data/data-helena-mysql:/var/lib/mysql
  command: /bin/true
# Mysql
mysql_helena:
  image: mariadb
  volumes_from:
  - mysql_data_helena
  ports:
   - "3306:3306"
  environment:
  - MYSQL_ROOT_PASSWORD=
  - MYSQL_DATABASE=Helena
  - MYSQL_USER=
  - MYSQL_PASSWORD=
# Link to PHP
php:
  links:
  - mysql_helena:mysql_helena