# Webstack Web data
web_data:
  image: ubuntu
  volumes:
  - ./www:/var/www/html
  command: /bin/true
# Webstack PHP
php:
  image: magiccyril/php:7-fpm
  volumes_from:
  - web_data
  ports:
  - "9000:9000"
# Webstack NGINX
nginx:
  image: nginx
  links:
  - php:webstack_php
  volumes_from:
  - web_data
  volumes:
  - ./conf/nginx.conf:/etc/nginx/nginx.conf
  - ./conf/nginx-conf.d:/etc/nginx/conf.d
  ports:
  - "8080:80"
# Webstack VARNISH
varnish:
  image: million12/varnish
  links:
  - nginx:webstack_nginx
  volumes:
  - ./conf/varnish.vcl:/etc/varnish/default.vcl
  ports:
  - "80:80"